### ISSUE TITLE
Capteur « couleur demain » ne s’alimente jamais

### ISSUE THREAD

**Issue by clerelus** [hekmon/linkytic#12]
Bonjour,
J’utilise votre programme sur un Lixee tic din sous Home Assistant.
Je suis avec un abonnement EDF Tempo.
Tout fonctionne à merveille sauf le capteur « couleur demain » qui n’affiche jamais l’information (même après 20h).
Savez-vous d’où peut venir ce problème ?
Merci et super travail.
Laurent

**Comment by hekmon** [comment]
Bonjour @clerelus,

Pour tout vous dire... J'ai eu le même "problème" que vous ! Déjà il faut savoir que le TIC n'envoie jamais l'information quand le jour est Bleu (seulement `----` comme tout le reste de la journée). Vous n'êtes donc pas prêt de voir quelque chose [puisqu'il ne reste que des jours bleus](https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html) jusqu'au prochain cycle en septembre.

Maintenant, même quand un jour blanc ou rouge est en approche, le fait que ce capteur ne s'active qu'à partir de 20h alors que l'information est publiée par RTE des 10h40 (si je ne m'abuse) n'est pas très pratique. Je suis moi même sous Tempo et j'ai vite ressenti le besoin d'avoir quelque chose de.... mieux.

J'ai donc développé une deuxième intégration intégralement dédiée à Tempo que je vous encourage à aller essayer (et qui se mariera très bien avec Linky TIC): [RTETempo](https://github.com/hekmon/rtetempo). Une pré-information publiée par RTE est récupérée vers les coups de 6h~6h30 du matin et cette dernière est confirmée dès 11h (plus d'information [ici](https://github.com/hekmon/rtetempo/issues/7)). Bien plus pratique.

Pour vous donner une idée de mon dashboard d'aperçu concernant l'électricité :
![image](https://github.com/hekmon/linkytic/assets/3418467/28c4086d-0bda-4b76-82dc-1c7445592b54)

**Comment by clerelus** [comment]
Bonjour @hekmon,
Un grand merci pour votre message rapide et complet (un jour férié en plus).
Je vais de suite intégrer vos conseils en installant RTE Tempo qui me semble plus adapté à mon besoin.
Merci encore et très bonne journée.
