### ISSUE TITLE
Pas possible d'ajouter au dashboard

### ISSUE THREAD

**Issue by ConvarDeutschland** [hekmon/linkytic#13]
Bonjour et merci pour votre intégration.

J'ai bien installé la version 2.05 par HACS . j'utilise le lixee tic din en /dev/ttyUSB1

Je retrouve l'intégration dans les paramètres Appareils mais qunad je clique dessous je n'ais pas les champs comme données en example sous le lien [[Exemple sous Home Assistant](https://github.com/hekmon/linkytic/raw/v2.0.5/res/SCR-20221223-ink.png).]

Je vois les entités, il y en a 24

Voici ce que je vois
![image](https://github.com/hekmon/linkytic/assets/14978257/e99cf578-ff15-4889-b823-eacd3139d319)

Est ce normal ou pas ? Qu'est ce que je peux faire

Cordialement

**Comment by hekmon** [comment]
Il est possible que cela soit lié à #14 je ne suis pas certain depuis quand le problème est apparu. Je vais me focaliser sur la correction de la #14 et nous verrons si cela corrige votre problème aussi.

Est-ce que les entités remontent des informations ? Que disent les logs de l'intégration ?

**Comment by hekmon** [comment]
Je ferme l'issue pour inactivité.
