### ISSUE TITLE
Erreur après mise a jour de core

### ISSUE THREAD

**Issue by ConvarDeutschland** [hekmon/linkytic#14]
Depuis la mise a jour de core de ce jour j'ai cette erreur:

ERROR (MainThread) [homeassistant.components.binary_sensor] linkytic: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'ENEDIS', 'default_model': 'Compteur communiquant Linky', 'default_name': 'Linky', 'identifiers': {('linkytic', '8cf004887b4e5242b31780c04d6df0ee')}, 'manufacturer': None, 'model': None} for 'linkytic' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by clerelus** [comment]
Bonjour,

Idem chez moi depuis ce matin avec la mise à jour HA Core en 2023.9.0.

linkytic: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'ENEDIS', 'default_model': 'Compteur communiquant Linky', 'default_name': 'Linky', 'identifiers': {('linkytic', 'XXXXXXXXXXXXXXXXXXXXX')}, 'manufacturer': 'ITRON', 'model': 'Compteur monophasé 60 A généralisation Linky G3 - arrivée puissance haute'} for 'linkytic' config entry: device info needs to either describe a device, link to existing device or provide extra information.

Merci

**Comment by hekmon** [comment]
Effectivement chez moi aussi les entités sont toujours là, mais plus dans l'appareil. L'appareil est toujours là mais sans entités.

On dirait que la manière de déclarer l'identifiant de l'appareil n'est plus valide. Il faut que je regarde, pas certain de pouvoir faire ca dans l'immédiat mais merci d'avoir remonté le problème.

---

> Bonjour, Meme chose de mon coté, je rajoute aussi :
> 
> ERROR (LinkyTIC for /dev/ttyUSB0) [custom_components.linkytic.serial_reader] Failed to parse the following line (1 fields detected) in historic mode: b''
> 
> Dispo au besoin, Merci !

Il s'agit d'une erreur différente d'une mauvaise ligne lue sur le lien TIC qui peut être "normale" et non liée à l'intégration en elle même. Un exemple sur https://github.com/hekmon/linkytic/issues/11#issuecomment-1590031286 (1ère erreur).

**Comment by superjaegermaster** [comment]
Hello, je confirme je viens de voir le même souci exactement immediatement après maj core

**Comment by hekmon** [comment]
La première erreur dans mes logs lié à l'appareil invalide date du 25 Août. On dirait que le problème existait avant la .9 mais est devenu visible que récemment.

**Comment by ToyNBoys** [comment]
> 

Oui j'ai deja notice ce pb dans la version 2023.8.3 mais c'était revenu en faisant un refresh
jai d'ailleur essayé un downgrade de HA en cette version et j'ai toujours le pb.

**Comment by hekmon** [comment]
Bon j'ai désormais les certitudes suivantes :

- Depuis la version du mois d'Août, Home Assistant n'aime plus la manière de déclarer l'appareil agrégeant les entités
- Ce n'était alors pas un problème bloquant : l'appareil était bien créé mais vide, sans entités rattachées et les entités continuaient de fonctionner dans leur coin (ce qui explique que je n'ai pas vu le problème plus tôt)
- Depuis la version 9 (de septembre) ce problème de déclaration d'appareil est devenu bloquant : les entités ne sont plus créés par Home Assistant à cause de leur lien invalide vers l'appareil

Par contre, je n'ai pas encore mis le doigt sur qu'est-ce qui fait que la déclaration de l'appareil n'est plus considérée comme valide... Je continue de chercher.

**Comment by ToyNBoys** [comment]
je viens d'ouvrir ma console ESX et je vois ca..
![screen](https://github.com/hekmon/linkytic/assets/70908371/417e932f-2978-4206-aa36-4b0be5bcba2e)

je pense pas que ca t'aide mais sait on jamais

**Comment by hekmon** [comment]
Cela devrait être corrigé avec la [v2.0.6](https://github.com/hekmon/linkytic/releases/tag/v2.0.6).

Pour ceux qui voudraient plus de détails :

- Les appareils sont maintenant [catégorisés en 3 types](https://developers.home-assistant.io/docs/device_registry_index/#categorizing-to-device-info) par Home Assistant et chacun de ces types ont un ensemble de propriétés à respecter. C'est à dire qu'il n'est plus possible de renseigner celles qui nous arrangent et d'en mélanger certaines.
- La déclaration précédente de l'appareil définissait à la fois un `default_manufacturer` et un `manufacturer` ainsi qu'un `default_model` et un `model`. Les defaults étant des constantes au cas où l'ADCO dont le vrai constructeur et modèle sont dérivés une fois la ligne lue sur le lien série (voir entité "Adresse du compteur").
- Mélanger les 2 n'est plus permis et la correction a été de définir les `manufacturer`, `model` et `name` (afin de correspondre à la définition de type `Primary`) et de retirer les `default_manufacturer`, `default_model` et `default_name` qui ne sont pas accepté en type `Primary` mais seulement `Secondary`.

Merci d'avoir porté le problème à mon attention et pour votre patience.

En attente de vos retours pour fermer (ou non) cette issue !

**Comment by ToyNBoys** [comment]
> 

cela semble bon de mon coté ! Merci encore Hekmon !
je pense me creer une instance HA differente specialement pour l'energie qui ne serait pas mise a jour, pour justement eviter cela... qu'en penses tu ?

**Comment by wkup** [comment]
Bonsoir,
Même problème en faisant la mise à jour ce matin.

Plusieurs traces dans les logs :

`Détails du journal (ERREUR)
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:621
Integration: Capteur binaire ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 21:01:06 (1 occurrences)
Last logged: 21:01:06

linkytic: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'ENEDIS', 'default_model': 'Compteur communiquant Linky', 'default_name': 'Linky', 'identifiers': {('linkytic', '91352f6da5a194c179aae1534d533446')}, 'manufacturer': 'SAGEM / SAGEMCOM', 'model': None} for 'linkytic' config entry: device info needs to either describe a device, link to existing device or provide extra information.`


`Détails du journal (ERREUR)
Logger: root
Source: helpers/entity.py:876
First occurred: 21:01:06 (1 occurrences)
Last logged: 21:01:06

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/config/custom_components/linkytic/serial_reader.py", line 144, in run
    notif_callback(forced_update)
  File "/config/custom_components/linkytic/sensor.py", line 807, in update_notification
    self.schedule_update_ha_state(force_refresh=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 876, in schedule_update_ha_state
    self.hass.create_task(
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_task'`

**Comment by hekmon** [comment]
> > 
> 
> cela semble bon de mon coté ! Merci encore Hekmon ! je pense me creer une instance HA differente specialement pour l'energie qui ne serait pas mise a jour, pour justement eviter cela... qu'en penses tu ?

Que cela représente plus de travail de maintenance pour vous @ToyNBoys :D
Après si la fiabilité et la disponibilité des informations liées à l'énergie est importante voir critique, cela peut s'entendre j'imagine !

Mais mon avis est certainement biaisé car si quelque chose se casse... je n'ai qu'à le réparer sans forcément dépendre de quelqu'un d'autre. C'est un plus ;)

---



> Bonsoir, Même problème en faisant la mise à jour ce matin.
> 
> Plusieurs traces dans les logs :
> 
> `Détails du journal (ERREUR) Logger: homeassistant.components.binary_sensor Source: helpers/entity_platform.py:621 Integration: Capteur binaire ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22)) First occurred: 21:01:06 (1 occurrences) Last logged: 21:01:06
> 
> linkytic: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'ENEDIS', 'default_model': 'Compteur communiquant Linky', 'default_name': 'Linky', 'identifiers': {('linkytic', '91352f6da5a194c179aae1534d533446')}, 'manufacturer': 'SAGEM / SAGEMCOM', 'model': None} for 'linkytic' config entry: device info needs to either describe a device, link to existing device or provide extra information.`
> 
> `Détails du journal (ERREUR) Logger: root Source: helpers/entity.py:876 First occurred: 21:01:06 (1 occurrences) Last logged: 21:01:06
> 
> Uncaught thread exception Traceback (most recent call last): File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner self.run() File "/config/custom_components/linkytic/serial_reader.py", line 144, in run notif_callback(forced_update) File "/config/custom_components/linkytic/sensor.py", line 807, in update_notification self.schedule_update_ha_state(force_refresh=True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 876, in schedule_update_ha_state self.hass.create_task( ^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'create_task'`

@wkup vous semblez utiliser la version 2.0.5, avez-vous essayé la version 2.0.6 mis en ligne il y a quelques minutes et indiqué [2 messages](https://github.com/hekmon/linkytic/issues/14#issuecomment-1710766044) plus haut ?

**Comment by ToyNBoys** [comment]
Merci pour votre avis ! Je vais ptet juste faire un snapshot avant de faire une Maj HA et voila... 
Oui cest important pour suivre ma conso et production et si vous etes en vacances ca peux etre chiant, nayant pas vos compétences dans ce domaine... 
Merci encore en tout cas encore beau boulot !

**Comment by ConvarDeutschland** [comment]
@hekmon La 2.06 marche pour moi, merci pour la rapidité de la mise en place d'une solution

**Comment by clerelus** [comment]
Bonjour,
Les données redescendent bien dorénavant sur les entités. Merci @hekmon pour cette réactivité et ce travail correctif de qualité.
Une remarque toutefois. La carte "Energie" de HA ne s'alimente pas de mon côté. Avez-vous constaté la même chose de votre côté ?
Merci

**Comment by ToyNBoys** [comment]
> Bonjour, Les données redescendent bien dorénavant sur les entités. Merci @hekmon pour cette réactivité et ce travail correctif de qualité. Une remarque toutefois. La carte "Energie" de HA ne s'alimente pas de mon côté. Avez-vous constaté la même chose de votre côté ? Merci

Salut, c'est ok de mon coté, regarde dans la "configuration de l'energie" voir si ton entité a pas sautée

**Comment by hekmon** [comment]
Vu que le problème semble corrigé, je clos cette issue. Mais vous pouvez bien entendu continuer à discuter dessus si nécessaire.
