### ISSUE TITLE
Support du mode standard

### ISSUE THREAD

**Issue by SebMourlhou** [hekmon/linkytic#15]
Bonjour,

D'abord un grand merci pour cette intégration très utile et aussi pour la réactivité en cas de pépin suite à des maj de HA.
Le choix d'architecture pour ne pas alourdir HA et quand-même la possibilité de passer en temps réel temporairement pour chercher les appareils consommateurs, vraiment c'est top !

J'envisage prochainement d'installer des panneaux solaires avec autoconsommation et revente du surplus. Si j'ai bien compris, mon Linky va devoir passer en mode standard pour avoir l'information sur la puissance injectée sur le réseau.

Dans la doc de l'intégration, il est dit que le mode standard n'est pour le moment pas supporté.
Y-a-t-il un espoir que ce soit supporté un jour ?

Merci

**Comment by hekmon** [comment]
Merci pour votre retour, quand on développe sur son temps libre les remerciements sont le seul salaire qui existe ;)

Et à propos de temps libre justement... L'évolution de ma vie personnelle m'en laisse de moins en moins malheureusement. Je ne pense pas que le support du mode standard devrait prendre très longtemps, un week end complet tout au plus car j'ai déjà implémenté le support théorique du standard série, il ne manque théoriquement que la création des entités Home Assistant et un peu de glue par ci par là.

Mais si l'expérience de développer le mode triphasé sur le mode historique m'a appris quelque chose c'est bien que ne pas pouvoir tester son développement est quasi chose impossible : impossible de savoir si cela marche, tout court ou partiellement, repérer des erreurs et faire les corrections. C'est pour cela que le mode triphasé est toujours en beta, il marche théoriquement je n'ai pas pu le tester. Cela ne donne pas une bonne qualité ou stabilité du code et ce n'est pas une expérience que je souhaite réitérer.

Seulement, le mode standard, je peux y passer moi même ce qui rend son développement faisable. Et je compte le faire, mais une fois passé au mode standard je dois être sûr d'avoir du temps derrière pour finir le développement ou je me retrouverai sans données dans mon Home Assistant.

Donc le mode standard oui, je veux le faire et je veux y passer. Par contre les conditions à réunir pour pouvoir le faire... Peut être l'été prochain quand j'aurai envoyé les enfants en vacances chez leurs grand parents ;)

**Comment by SebMourlhou** [comment]
D'acc, je comprends. Merci encore
