### ISSUE TITLE
Index re-Injection

### ISSUE THREAD

**Issue by ToyNBoys** [hekmon/linkytic#16]
Bonjour @hekmon,

il y a une possibilité de recuperé l'index reinjection ou pas ?

Merci !

**Comment by hekmon** [comment]
Pas en mode historique malheureusement, il faut activer le mode standard normalement (mais l'intégration ne le supporte pas... encore).

**Comment by gduteil** [comment]
Salut et merci pour ton travail @hekmon

Je viens de commiter un début du support du mode standard https://github.com/gduteil/linkytic
Je ne fais pas de réinjection mais normalement les messages devraient être connectés

Guizmo

**Comment by hekmon** [comment]
La suite dans #19

**Comment by hekmon** [comment]
En conclusion :
- Les index d'injections ne peuvent être récupérés qu'avec le mode `standard`
- Les Linky sont par défaut en mode `historique` : il faut faire la demande à Enedis pour le passer en mode `standard`
- Il est fortement probable qu'Enedis passe votre Linky en TIC `standard` une fois que vous avez fait la déclaration nécessaire pour la réinjection dans le réseau
- Le mode standard est supporté par le module à partir de la v3 (actuellement en beta)

**Comment by ToyNBoys** [comment]
Salut @hekmon,
J'ai passé mon compteur en mode std, je suis passé en v3 last beta, tout est ok !
par contre je ne vois pas mon injection ?
est-il possible d'avoir aussi ma conso en temps réel en W ? 
mon ecojoko me la donne, j'ai avec le capteur a poser sur le compteur et non pas les broches (afin d'avoir mon suplus solaire)
merci !

**Comment by gduteil** [comment]
Les index d'injection sont à 0 ?
Il est possible qu'ils ne soient pas remontés par le Linky si la réinjection se fait sans contrat de rachat par Enedis

**Comment by ToyNBoys** [comment]
Salut @gduteil !
oui c'est ca, a 0 et en effet j'ai pas de contrat de rachat, par contre dans les menu du linky jai bien des valeurs a l'intitulé : index injection...

**Comment by gduteil** [comment]
Il y a 10 entités spécifiques au mode producteur, elles sont toute à 0 ?

Y a-t-il dans les autres index une valeur correspondante à ce qu'affiche le Linky ?

**Comment by ToyNBoys** [comment]
Salut @gduteil elles sont "indisponible" 
ex: 
![image](https://github.com/hekmon/linkytic/assets/70908371/2460ad34-1ddd-4d60-a7e6-dd3a6709d7cc)

**Comment by gduteil** [comment]
C'est soit qu'elle ne sont pas remontées, soit qu'elle sont mal interprétées.
Il y a des erreurs ou des infos sur les trames "EAIT", "ERQx", "SINSTI" dans les logs ?

L'entité "Linky Statut producteur/consommateur" évolue ou reste en "consommateur" ?
