### ISSUE TITLE
deux points de trop HP.. et HC ..

### ISSUE THREAD

**Issue by sigalou** [hekmon/linkytic#17]
Bonjour,

Je viens d'installer cette intégration (en 3 min merci !) sur HA
Elle fonctionne parfaitement.
Mon équipement TIC est un module DIN (Cartelectronic USBTIC).
J'ai deux points qui trainent sur les valeurs HP et HC. Ce n'est pas dramatique mais dommage. Tu aurais moyen de les filtrer ?
![image](https://github.com/hekmon/linkytic/assets/26350534/ed2a84c0-eef3-4554-b5b1-8ee627b7b247)

Dispo si besoin ou questions, a+

**Comment by hekmon** [comment]
Bonjour,

Merci pour votre retour !

J'ai bien conscience que certaines valeurs sont... particulières. Par exemple l'offre tarifaire choisie (je suis sous Tempo) est remontée comme `BBR(` chez moi : autant BBR je comprends (Bleu Blanc Rouge) autant la parenthèse à la fin je ne sais pas pourquoi le standard TIC l'envoi.

Mais cela est justement le sujet ; je souhaite que cette intégration remonte _exactement_ ce que le standard TIC renvoie sans modifier les informations. Si le standard remonte `HC..` et `HP..` c'est ce que je souhaite que l'intégration affiche :)

Si vraiment c'est un sujet pour vous, vous pouvez toujours vous lancer dans un [template sensor](https://www.home-assistant.io/integrations/template/) pour afficher ce dont vous avez envie, en vous basant sur celle fournie par l'extension.

**Comment by sigalou** [comment]
Hello,

ça marche, l'argumentaire est propre, que l'intégration rapporte en brut et l'utilisateur traite me convient très bien.
Je lai signalé en pensant que c'était une erreur et qu'une petite fonction pouvait supprimer dans le code les ..

Je vais voir si ce .. est gênant et oui, tu as raison, je peux le traiter avec un template en 2 min.

Au plaisir, merci pour ton support.
