### ISSUE TITLE
Paramétrage avec le dashboard Energie

### ISSUE THREAD

**Issue by Skuair** [hekmon/linkytic#18]
Bonjour,

J'ai récemment acquis le Lixee TIC DIN et j'ai pu installer ce plugin, merci pour le travail.
Je pense avoir loupé un truc avec le dashboard Energie : en effet, en parcourant les issues et notamment ce commentaire https://github.com/hekmon/linkytic/issues/8#issuecomment-1482679640 vous dites bien que le plugin fournit les entités energy pour les utiliser dans le dashboard. Mais de mon côté elles n'apparaissent pas.

Que faut-il que je fasse ? Activer le recorder pour ces entités (je choisis moi-même quelles entités je veux conserver en historique actuellement) ?

Voici le résumé de l'intégration:
![image](https://github.com/hekmon/linkytic/assets/49756503/a9b478aa-c609-4d3c-9024-c671645ed8b5)

Et sur le dashboard energy en paramétrage (la seule entité qu'on voit dans la liste est celle d'un ancienne intégration que je vais enlever quand tout sera ok avec le TIC) :
![image](https://github.com/hekmon/linkytic/assets/49756503/d9ee15e9-f1d7-4c6f-9992-217ef9c93702)

Et enfin, si ça peut influencer, voici le paramétrage de mon recorder :
![image](https://github.com/hekmon/linkytic/assets/49756503/26acd1b7-01e4-42b4-9575-d3edb302ddf8)

Merci d'avance.

**Comment by hekmon** [comment]
Bonjour,

Cela est étrange. Aucun configuration particulière n'est normalement nécessaire.

Si vous allez dans les outils developper et que vous filtrez les sensors avec `sensor.linky_index_option` qu'est-ce que cela vous donne pour vos deux index ?
![image](https://github.com/hekmon/linkytic/assets/3418467/69e9664d-3707-4a93-a982-5cc706f4cc34)
L'important est d'avoir `device_class: energy` et `unit_of_measurement: Wh` de mémoire (et certainement `state_class: total_increasing`) pour que que HA le propose dans le dashboard energie. 

Aussi... quelle version de HA ? :)

**Comment by Skuair** [comment]
J'ai bien les 3 attributs nécessaires pour les 2 index options heure plaines et creuses :
state_class: total_increasing
unit_of_measurement: Wh
device_class: energy
![Screenshot_20231006-061627](https://github.com/hekmon/linkytic/assets/49756503/f7dfe764-a2a4-46d9-9ae0-2634d5974437)

Version de HA toute dernière 2023.10.0, mais avec la dernière de septembre c'était pareil.
Il n'y a pas de rapport avec le recorder ?

**Comment by hekmon** [comment]
Normalement aucun lien avec le recorder (HA créer des sensors de rollup tout seul apres avoir passé le wizard du dashboard energy).

Je vois que vous avez un sensor qui apparait dans la liste comme compatible (MyElectricalData-...). Quels sont ses attributs ?

**Comment by Skuair** [comment]
Justement, ces sensors dispo de l'ancienne intégration, je ne les trouve pas avec l'outil de développement. On dirait que ce sont des sensors cachés.
Avec cette ancienne intégration, pour les avoir dispo avec l'onglet énergie, il avait fallu faire quelque chose de spécifique (une sorte de config pour une communication websocket : https://github.com/MyElectricalData/myelectricaldata_import/wiki/03.-Configuration#home_assistant_ws), mais c'est sûrement spécifique à cette intégration.

Du coup je ne sais pas trop quoi debugger pour vous donner plus d'infos.

**Comment by hekmon** [comment]
Mmmm je ne vois aucune raison qui empecherait le sensor d'être détecté... Ce qui m'embête c'est que vous êtes le 2eme à avoir ce problème semble-t-il et qu'il n'y a pas l'ombre d'une piste.

Quelques idées pour vous aider à continuer la recherche :
- voir sur les forums Home Assistant pourquoi vous ne pouvez pas ajouter ce compteur dans le dashboard énergie (vous savez maintenant afficher les propriétés d'un senseur, cela vous sera certainement demandé)
- tentez de faire des sensors virtuels avec l'integration [template](https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors) et essayer de changer une des propriétés. Je pense par exemple a faire un sensor avec les même propriétés mais changer la `unit_of_mesurment` en `kWh` par exemple et donc utiliser le template pour diviser par 1000 la valeur du sensor d'origine. Dans l'onglet développeur vous avez de quoi tester votre template sous l'onglet `modèle`. Et voir si ce nouveau sensor virtuel arrive à être vu par le dashboard énergie.

Bon courage pour votre recherche et n'hésitez pas à revenir ici pour de l'aide ou partager vos résultats.

**Comment by Skuair** [comment]
J'ai trouvé, c'était bien un problème de recorder.

En effet, en allant dans outils de développement / statistiques, les 2 sensors en question étaient en "problème", notamment car ils n'était pas pris en compte par le recorder :
![image](https://github.com/hekmon/linkytic/assets/49756503/93ebe4a1-8e48-4b4d-b1b2-07c67935b8d1)

En les ajoutant à ma config comme suit :
![image](https://github.com/hekmon/linkytic/assets/49756503/e5e5e890-5045-4fe3-a2fc-d6d21ff2f8f5)

Je peux maintenant les sélectionner dans le dashboard energy :
![image](https://github.com/hekmon/linkytic/assets/49756503/ff23cd04-8c0a-4729-9344-f64ca5c5bc71)

Question subsidiaire : que mettez-vous pour le suivi des coûts ? entité de suivi des coûts totaux, entité avec prix actuel ou prix fixe ?
Je vois un sensor sensor.linky_index_option_heures_creuses_heures_creuses_cost et sensor.linky_index_option_heures_creuses_heures_pleines_cost, faut-il utiliser ces 2 ? Comment sont-ils remplis ?

**Comment by hekmon** [comment]
Bonne nouvelle ! Bravo pour avoir trouvé.

En effet, après lecture de la [documentation du recorder](https://www.home-assistant.io/integrations/recorder/#configuration-variables) il se trouve que l'entrée `include` :

- Normalement vide, le comportement par default est de prendre en compte toutes les entités compatibles
- Dès que vous spécifiez ce paramètre seul les entités listées seront enregistrées

Votre premier message indique effectivement que vous possédiez une configuration particulière avec un `include`, par conséquents les entités d'index de l'intégration n'étaient plus enregistrées et donc n'apparaissaient pas dans le dashboard énergie.

Une configuration par default du recorder (j'entends sans `include` spécifié) aurait de fait inclus les entités d'index du Linky et n'aurait pas bloqué leur apparition dans le dashboard énergie.

Ce n'est pas un point potentiel de blocage que je connaissais (je n'ai pas de configuration particulière de mon recorder a part pour la rétention). Mais cela servira certainement à d'autres personnes, merci d'être revenu partager la solution !

Concernant le suivi des coûts, j'utilise une entité fixe de type input que je mets a jour manuellement. Vous pouvez voir le détails en regardant l'exemple "Affichage dynamique des prix" dans le readme de mon intégration [Tempo](https://github.com/hekmon/rtetempo#exemples-de-cartes-lovelace).

**Comment by Skuair** [comment]
Oui pour les prix, j'ai compris après coup que c'était HA qui avait créé le sensor xxx_cost selon la config que je lui avait donné.
J'ai utilisé le mode prix fixe en paramétrage du dashboard energy, mais une entité de type input_number ferait très bien l'affaire aussi.
Merci à vous.
