### ISSUE TITLE
Sensors non fonctionnels suite à mise à jour HA 2023.11

### ISSUE THREAD

**Issue by Skuair** [hekmon/linkytic#22]
Bonjour,
Depuis la mise à jour vers HA 2023.11, un message d'erreur apparaît dans les logs concernant l'intégration, et les sensors retournent des données pendant quelques minutes mais après restent à leur dernière valeur (en particulier celui de la puissance apparente ou des index).

Voici les 2 erreurs au lancement de HA :

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Capteur (documentation, issues)
First occurred: 12:33:33 (1 occurrences)
Last logged: 12:33:33

Error adding entities for domain sensor with platform linkytic
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.linky_option_tarifaire_choisie cannot be added as the entity category is set to config

---

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Capteur (documentation, issues)
First occurred: 12:33:33 (1 occurrences)
Last logged: 12:33:33

Error while setting up linkytic platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.linky_option_tarifaire_choisie cannot be added as the entity category is set to config

A partir de là, il semble qu'on reçoive une seule valeur sur les sensors mais après plus rien, comme on peut le voir sur les historiques (les escaliers sont quand j'ai redémarré HA : hier soir après la maj, et ce midi j'ai redémarré 2 fois pour voir les erreurs) :
![Screenshot_20231102-124045](https://github.com/hekmon/linkytic/assets/49756503/f6757867-3c15-4773-962a-8cf6c7078642)
![Screenshot_20231102-124145](https://github.com/hekmon/linkytic/assets/49756503/2cb7e0d9-fc3a-4625-9d66-03733329666c)

**Comment by hekmon** [comment]
Bonjour,

J'ai bien vu passer le problème. Il semblerait que depuis la 2023.11 les sensors n'ont [plus le droit](https://github.com/home-assistant/core/commit/f7292d5b00100d04f3a0f967595becb716b45b7c) d'être de type "config".

Pour être un peux plus précis :
* Certains sensors remontent des informations liés au contrat, j'avais donc placé ces derniers sous le type config puisque c'est quelque chose que l'utilisateur a "configuré"
* Seulement pour HA en 2023.11, un sensor étant "read only" ces derniers ne peuvent pas être de type config : pour HA une entitée de type config doit pouvoir changer quelque chose/provoquer une action (de reconfiguration)
* L'erreur semble bloquer l'initialisation du plugin et donc des autres entitées.

La correction devrait être simple, je m'y penche dès que possible.

**Comment by Skuair** [comment]
Ok super merci.

**Comment by hekmon** [comment]
Disponible avec la [v2.0.7](https://github.com/hekmon/linkytic/releases/tag/v2.0.7)

**Comment by Skuair** [comment]
Merci pour la modif, c'est ok maintenant.
