### ISSUE TITLE
Impossible de récupérer les informations du compteur (Failed to parse)

### ISSUE THREAD

**Issue by theoricher** [hekmon/linkytic#24]
Bonjour,

Je rencontre un souci avec l'extension et le module [TIC-DIN](https://lixee.fr/produits/30-tic-din-3770014375070.html) 
L'ensemble des capteurs restent dans un état : Inconnu sauf la connectivité du lien série qui elle est bien en état : Connecté

J'ai réinstallé le module, mais aucun changement.

Au niveau des logs j'ai l'erreur ci-dessous, de ce que je comprends il n'arrive pas à décoder les informations renvoyer par le module ?

```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.linkytic.serial_reader
Source: custom_components/linkytic/serial_reader.py:284
Integration: Linky TIC (documentation, issues)
First occurred: 00:41:44 (45332 occurrences)
Last logged: 13:19:16

Failed to parse the following line (1 fields detected) in historic mode: b'\xfe\x02a\x01\x00'
Failed to parse the following line (1 fields detected) in historic mode: b''
Failed to parse the following line (1 fields detected) in historic mode: b'\xfe\x06A\x80\x00\x02\x01'
Failed to parse the following line (1 fields detected) in historic mode: b'\xfe\x02a\x01Y'
Failed to parse the following line (1 fields detected) in historic mode: b'\xfe\x02a\x01'
```

Voici une capture des capteurs :
![image](https://github.com/hekmon/linkytic/assets/12476264/80cf7e4d-e379-4855-be5d-9e392852ab70)

**Comment by hekmon** [comment]
Il semble effectivement qu'aucune ligne de la connexion série ne puisse être lue correctement.

Avez-vous réussi à obtenir une sortie correcte en série tout d'abord (avant même de parler du module HA) avec la procédure décrite dans la [configuration](https://github.com/hekmon/linkytic#configuration-du-module) ?

**Comment by theoricher** [comment]
Bonjour, 

Merci pour ce retour rapide, il semblerait que le Raspberry c'était perdu dans les /dev/ttyUSBX.
J'ai débranché la clé ZIGBEE + le TIC-DIN reboot le Raspberry.
Une fois HA de démarré j'ai rebranché les périphériques et le module a récupéré les informations correctement.

Merci pour votre aide elle m'a permis de mieux détecter l'origine du problème. 👍 

Excellente soirée à vous !

**Comment by hekmon** [comment]
Bonjour @EMqA44,

Comme expliqué [ici](https://github.com/hekmon/linkytic/issues/26#issuecomment-1953142907), pouvez-vous ouvrir une nouvelle issue pour votre problème ?

Merci.
