### ISSUE TITLE
pas de texte - ajoutez une entrée

### ISSUE THREAD

**Issue by yves67** [hekmon/linkytic#30]
avec la beta 3., de linktic, si je sélectionne ajoutez une entrée il s'affiche le'écran suivant : 

![image](https://github.com/hekmon/linkytic/assets/8557996/f1974f83-22a7-4fd0-8ec8-50c1b9507bad)

il n'y a pas de texte à coté des selecteurs 

même chose pour l'écran configurer : 

![image](https://github.com/hekmon/linkytic/assets/8557996/f19a73a1-c410-4bf6-900d-7498751d4f7e)

Yves`

**Comment by hekmon** [comment]
je me demande si ce n'est pas lié à mon [hypothèse](https://github.com/hekmon/linkytic/issues/29#issuecomment-1952926620) sur votre autre issue #29 .

Réglons déjà la première et voyons si la seconde persiste ensuite.

**Comment by hekmon** [comment]
https://github.com/hekmon/linkytic/issues/29#issuecomment-1953103637
