### ISSUE TITLE
Plus de remontées suite passage en version os 12

### ISSUE THREAD

**Issue by DizHell** [hekmon/linkytic#34]
J'ai passé la mise à jour d'os en version 12 hier matin.
Pas de Big de remontées sur la journée et la ce matin plus aucune remontée des entités.

J'ai toujours 2 capteurs comme avant avec un de désactiver car vierge, mais même en activant le deuxième et en redémarrant home assistant et son os rien a faire il ne fonctionne plus.
Je suis en version release. 2.0.7

**Comment by DizHell** [comment]
Le port USB est bien déclaré (/dev/ttyUSB0) le module tic est bien actif je vois la led d'activité qui clignote normalement.

Et de ce que je vois sur les logs il a perdu la connexion a 12h06 et je n'avais aucune manipulation manuel ou automatisme de lancé a ce moment là.

**Comment by DizHell** [comment]
Le port USB est bien déclaré (/dev/ttyUSB0) le module tic est bien actif je vois la led d'activité qui clignote normalement.

Et de ce que je vois sur les logs il a perdu la connexion a 12h06 et je n'avais aucune manipulation manuel ou automatisme de lancé a ce moment là.

Édit :
J'ai testé un cat /dev/ttyUSB0 
pas de réponse. J'ai donc reconfigurer le port avec :
stty -F /dev/ttyUSB0 1200 sane evenp parenb cs7 -crtscts

Et le Cat suivant était fonctionnel. Mais toujours pas de remontées sur HA, je redémarre alors juste Home Assistant... Mais toujours rien.
Je test alors un redémarrage du système...
Toujours rien et en retestant un cat je n'ai plus rien n'ont plus.

**Comment by DizHell** [comment]
J'ai réussi à le refaire fonctionner, pour cela j'ai désactivé l'élément de l'intégration, et je l'ai réactiver manuellement 10sec plus tard et là il est de nouveau fonctionnel.

Bizarre que mes 3-4 tentatives de reboot du système n'aient pas eu le même effet.

**Comment by jduquennoy** [comment]
Petite note sur un soucis que j'ai eu de mon côté : les path du type /dev/ttyUSB0 ne sont pas forcément stables : apres un redémarrage, il est possible que le périphéirque USB s'appelle ttyUSB1 ou ttyUSB2.
La solution que j'ai adopté de mon coté consiste à utiliser un path de type /dev/serial/by-id/...

Sur un linkytic non modifié, le path devrait être
/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0

**Comment by DizHell** [comment]
> La solution que j'ai adopté de mon coté consiste à utiliser un path de type /dev/serial/by-id/...
> 
> Sur un linkytic non modifié, le path devrait être
> /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0

Oui mais de ce que j'ai vu le mode par patch ne fonctionne qu'avec la version beta, et dans tout les cas comment faire pour le changer sans perdre mon histoire actuel ?

**Comment by DizHell** [comment]
Bon il a encore saute ce matin, et de ce que je vois mon module USB Tic n'est plus reconnu sur proxmox.
Je viens de tester update de proxmox et reboot mais sans succés, je regarderai pour le rebrancher à midi.
Vous utilisez quoi comme module ? j'ai un collégue qui en à un en Wifi mais il a pas les bonne unité de mesure.
J'ai repéré un model Zigbee, mais a savoir si ce sera mieux que mon model usb...

**Comment by jduquennoy** [comment]
> Oui mais de ce que j'ai vu le mode par patch ne fonctionne qu'avec la version beta, et dans tout les cas comment faire pour le changer sans perdre mon histoire actuel ?

Je ne suis pas sûr de savoir de quel mode patch il s'agit.
Quoi qu'il en soit, il me semble que le path peut être modifié dans la configuration du module. Ca ne devrait pas poser de problème de perte de données. Mais quoi qu'il en soit, il est toujours prudent de faire une sauvegarde si on a des craintes de perte de données :-)

**Comment by jm-github** [comment]
Bonjour,
j'ai pour ma part un USBTIC de cartelectronic et de temps en temps il ne transmet plus de données. Je n'ai pas réussi à déterminer une procédure fiable pour le refaire fonctionner.
Par contre j'ai remarqué que le dysfonctionnement survient uniquement au changement de période tarifaire. Je suspecte le module de ne pas supporter les perturbations électromagnétiques générées par le contacteur de mon chauffe eau qui est placé juste à côté dans le tableau électrique.

Pour ma part j'utilise la version 2.0.7 en mode historique avec le chemin /dev/serial/by-id

**Comment by hekmon** [comment]
Personnellement j'utilise celui de LiXee qui ne m'a jamais posé problème. Attention aussi a la connection entre la prise TIC et le module USB qui peut souffrir de la polution electromagnetique (j'utilise une cable electrique 2 voies standard type lampe avec une bonne epaisseur plastique autour de fil de cuivre).

La plus part des problèmes remontées ici ne viennent souvent pas de l'extension en elle même mais de la partie physique avant (le cable, le module USB, l'intégration du module USB au systeme). L'intégration ne faisant que lire les données du lien série, elle ne peut rien y faire si les données remontées présentent un problème ou des incohérences du à un problème de module ou d'installation.

Je me permet de fermer l'issue vu que le problème ne semble pas être lié à l'extension en elle même.
