### ISSUE TITLE
Déconnexion Tic

### ISSUE THREAD

**Issue by DizHell** [hekmon/linkytic#39]
Bonjour,
J'ai encore des déconnexions aléatoires, du coup cela m'oblige à faire des reboot de home assistant pour le résoudre.

Au début c'était la nuit que j'avais le problème pourtant pas de programmation particulière en parallèle. Et ce n'était pas toutes les nuits...

J'avais programmé un reboot automatique journalier mais des fois il plantait juste après.

J'ai supprimé totalement le module tic, car il détecté 2 port série. Au moment de le refaire j'ai mis directement le nom du port et je n'ai plus eu de problème pendant 4jours puis de nouveau plantage, voici l'erreur détecté dans les logs :

```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.linkytic.serial_reader
Source: custom_components/linkytic/serial_reader.py:284
intégration: Linky TIC (documentation, problèmes)
S'est produit pour la première fois: 4 août 2024 à 02:02:30 (25270 occurrences)
Dernier enregistrement: 08:28:55

Failed to parse the following line (1 fields detected) in historic mode: b''
Failed to parse the following line (2 fields detected) in historic mode: b'\x05j\x0eZ\x144-\x1c(j\x0e\x1dT\x1c]<\x1d<&lL\x1c\x180 B'
Failed to parse the following line (2 fields detected) in historic mode: b'ADCO 06196'
Failed to parse the following line (5 fields detected) in historic mode: b'HHPHC A ,\rMOTDETAT 000000 B'
Failed to parse the following line (1 fields detected) in historic mode: b'OP'
```

J'ai un ticUSB de ce type 
[https://www.tindie.com/products/hallard/micro-teleinfo-v30/]()

**Comment by DizHell** [comment]
J'ai peut être un début de piste, j'ai chercher un peu plus au niveau de la base de mon Home assistant OS qui est hébergé sur un Nucléaire sous Proxmox, j'ai vu dans mes logs Proxmox que j'avais des erreurs fréquentes de Nuts qui ne trouvait pas d'onduleur en USB, normal vu que j'ai l'onduleur sur mon Synology et il le partage ces info au Nuts du Proxmox par négociation IP.
Du coup j'ai réussi a désactiver la partie USB de Nuts et depuis plus de problème pour l'instant avec le module Tic a voir sur la durée si c'est la bonne piste...

**Comment by hekmon** [comment]
J'en déduis que tout va bien depuis ?

**Comment by tomleglaunec** [comment]
J'ai à peu près la même configuration (Proxmox + HA OS + uTeleInfo-v3.0) et aucun problème de données. Les logs ne ressemblent pas à une trame TIC. HA se connecte surement sur un port UART /dev/ttyACMx lesquels ne sont pas forcément persistants. Le problème devrait être résolu avec #32 avec le passage de la configuration du chemin en `by-id`.

Pour info, je map le port USB depuis Proxmox directement depuis le VID:PID :

![image](https://github.com/user-attachments/assets/c55c6939-c5c1-4289-823b-a2b1504f71ea)
