### ISSUE TITLE
Crash de home assistant avec module Teleinfo de ADTEK

### ISSUE THREAD

**Issue by MatthieuLaurent** [hekmon/linkytic#40]
Hello,

Merci beaucoup pour cet intégration très utile !
Avec un module Teleinfo ADTEK (type : https://doc.eedomus.com/view/T%C3%A9l%C3%A9info_USB_ADTEK), l'utilisation fait complétement planter HA (perte de l'interface web notamment...)
Aucune trace d'erreur dans les logs, ni de plantage en debuggant... 
Au bout de quelques essais  j'ai pu identifier le problème : le baudrate du module est de 9600 bien que mon Linky soit en mode historique. Résultat, le readline ne détecte pas le caractère de fin de ligne, ne s'arrete jamais et fait tout planter...
La solution que j'ai trouvée est de remplacer le baudrate à 9600 pour le mode historique dans le const.py, sans rien modifier par ailleurs. La config se passe bien en mode historique ensuite.

Je ne suis pas vraiment capable de proposer une autre correction, mais on peut tracer la solution pour d'autres qui auraient ce problème.

**Comment by hekmon** [comment]
Je l'ai rajouté dans le readme, merci pour les autres ;)

**Comment by Tigrou750** [comment]
En fait, il y a plusieurs configuration possible  sur ce modèle

Deux switchs internes permettent d'avoir quatre configurations différentes (ouvrir délicatement le boîtier pour ne pas casser les pions en plastique, si nécessaire) :
•   1 et 2 sur ON (ON à gauche, le 1 est en bas, le 2 en haut) : flux série identique à celui du compteur, non modifié, 1200 bauds, 7 bits, parité paire
•   1 sur OFF et 2 sur ON :  fonctionnement identique, 1200 bauds, 7 bits, parité paire, mais le flux série ne démarre que 64 secondes après la mise sous tension de l'adaptateur téléinfo
•   1 sur ON et 2 sur OFF :  fonctionnement identique, 1200 bauds, 7 bits, parité paire, mais le flux série ne démarre que 256 secondes après la mise sous tension de l'adaptateur téléinfo
•   1 et 2 sur OFF : mode compatible Téléinfostick (sélectionner ce mode dans iTow par exemple), 9600 bauds, 8 bits, pas de parité
Ce dernier mode sera bien sûr la configuration préférée pour éviter radicalement les problèmes de souris folle (configuration de livraison en principe). Les modes avec temporisation seront utilisés avec les logiciels n'acceptant que le 1200 bauds, et les durées doivent permettre de passer la découverte automatique des souris avant que le flux série n'ait commencé. Mais en cas de reset à chaud, cette parade ne sera pas efficace.
Un logiciel comme RealTerm sur PC est très efficace pour tester la réception série.


Source: https://itow.fr/Forum/index.php?msg=1767
