### ISSUE TITLE
Linky G1 pilote non reconnu (ADS 67)

### ISSUE THREAD

**Issue by jipem01** [hekmon/linkytic#41]
Bonjour,

Dans les journaux du module :
2024-10-27 23:18:00.322 WARNING (LinkyTIC for /dev/ttyACM1) [custom_components.linkytic.serial_reader] /dev/ttyACM1: ADS device type is unknown: 67

En regardant le document : "res\IdentifiantsEuridisListeCCTTV304A_143027.pdf", on lui trouve bien une définition : "Compteur monophasé 90A LINKY - pilote G1 - arrivée basse (300 000 ex.) "

**Comment by jipem01** [comment]
Proposed fix in PR #44

**Comment by hekmon** [comment]
Mergé ! upcoming 3.0.0-beta4
