### ISSUE TITLE
Linky G1 pilote ne remonte pas la puissance instentannée.

### ISSUE THREAD

**Issue by jipem01** [hekmon/linkytic#42]
Sur un compteur Linky phase pilote (ADS type 67), les entités suivantes sont indisponibles :
- Puissance app. instantanée soutirée, 
- Puissance app. max. soutirée n
- Puissance app. max. soutirée n-1

**Comment by jipem01** [comment]
Proposed fix in PR #44

**Comment by hekmon** [comment]
Mergé ! upcoming 3.0.0-beta4
