### ISSUE TITLE
plus de classe d'état

### ISSUE THREAD

**Issue by yves67** [hekmon/linkytic#47]
je viens d'installer la dernière version 3.04B et j'ai 10 erreurs me disant que ces capteurs n'ont plus de classe d'état ?? 

![image](https://github.com/user-attachments/assets/f626088d-2779-448c-8c4a-5ea1af820156)

que faut-il faire ?

**Comment by hekmon** [comment]
C'est normal pas d'inquiétude.

Ces senseurs n'ont pas d'intérêt à avoir une classe d'état, l'enlever va soulager un peu la base de données. Il faut simplement supprimer les anciennes statistiques voir https://github.com/hekmon/linkytic/pull/32#issuecomment-2479923753 pour plus d'infos.

**Comment by yves67** [comment]
merci beaucoup

*Yves VOUIN - 06 75 87 43 34*


Le sam. 16 nov. 2024 à 11:02, Edouard Hur ***@***.***> a
écrit :
