### ISSUE TITLE
Problème dans la définition de la couleur

### ISSUE THREAD

**Issue by Anoxym** [hekmon/linkytic#52]
Bonjour,

Je viens de passer à l'offre tempo et je rencontre un soucis, j'ai un linky en triphasé et j'étais auparavant sur une offre HC et cela fonctionnait bien je récupérai la conso HC/HP.

Maintenant que j'ai l'offre tempo, la période tarifaire indiquée est HCJB alors que ce jours est en rouge, et du coup la valeur de conso pour HC jours rouge ne compte pas

![image](https://github.com/user-attachments/assets/3e420ba2-2677-4aa8-bd55-a05a9e69ca4c)

![image](https://github.com/user-attachments/assets/2efd2643-9626-45c3-b049-bb10984cde33)

Sauriez vous d'où viens ce bug ? Je suis en version 3.0.0-beta3

Merci

**Comment by pjeantaud** [comment]
On sera en Rouge dans 10 minPatrick JEANTAUDEnvoyé de mon iPadLe 10 déc. 2024 à 00:51, Anoxym ***@***.***> a écrit :﻿
Bonjour,
Je viens de passer à l'offre tempo et je rencontre un soucis, j'ai un linky en triphasé et j'étais auparavant sur une offre HC et cela fonctionnait bien je récupérai la conso HC/HP.
Maintenant que j'ai l'offre tempo, la période tarifaire indiquée est HCJB alors que ce jours est en rouge, et du coup la valeur de conso pour HC jours rouge ne compte pas
Upload.from.GitHub.for.iOS.png (view on web)
Upload.from.GitHub.for.iOS.png (view on web)
Sauriez vous d'où viens ce bug ? Je suis en version 3.0.0-beta3
Merci

**Comment by Anoxym** [comment]
Non je confirme on est actuellement en heure pleine rouge (HPJR j'imagine) et à l'heure de mon commentaire cela devait être HCJR (heure creuse rouge de 22h à 6h)

![image](https://github.com/user-attachments/assets/d0f0748b-03e0-42b4-ba42-aba08de13b93)

**Comment by pjeantaud** [comment]
Non, les jours Rouges commencent à 6H et se terminent à 6H, donc à l’heure de ton post, on était en HP Blanc.

**Comment by tomleglaunec** [comment]
Bonjour, pour vérifier quel index est effectivement actif à un temps donné tu peux essayer de corréler les valeurs de ce capteur avec les compteurs HC/HP bleu blanc rouge (voir historique dans home assistant)

N'ayant ni trames historiques ni contrat couleur, je ne peux pas aider plus sur le décodage des index, cependant ils sont remontés tels que lu sur la TIC.

**Comment by Anoxym** [comment]
![image](https://github.com/user-attachments/assets/400b1a49-7c95-4fca-9109-c8e35b282f44)

**Comment by pjeantaud** [comment]
Tu viens juste d'activer Tempo, je crois. Le 1er jour Rouge est cadeau, tu seras facturé en Bleu.

Chez moi:
![Capture d’écran 2024-12-10 à 09 31 49](https://github.com/user-attachments/assets/f6591cfa-b75c-4c4b-a38c-05537cdcac9a)

**Comment by Anoxym** [comment]
Ah d'accord dans ce cas cela pourrait expliquer le problème, j'irai voir sur le compteur ce qu'il affiche 
Par contre le fait que mes compteurs n'augmentent pas au niveau de la consommation je ne sais pas pourquoi?

**Comment by pjeantaud** [comment]
Je crois qu'il faut 2H pour que les compteurs soient propagés au TDB Energie.
Au niveau Sensor, tu as bien Fournisseur et non Distributeur ?

**Comment by Anoxym** [comment]
> Je crois qu'il faut 2H pour que les compteurs soient propagés au TDB Energie.
> 
> Au niveau Sensor, tu as bien choisi Fournisseur et non Distributeur ?

À quel endroit fait-on ce choix ? 
Initialement j'ai attendu le changement d'offre et les entités tempo sont devenues actives, n'ayant pas vu d'augmentation de consommation j'ai supprimé le device et je l'ai recréé en choisissant le mode historique et three phase

**Comment by pjeantaud** [comment]
Peut être devrais tu upgrader en beta 4 ?
Moi je suis en Standard, Tempo, Monophasé et Producteur.

**Comment by Anoxym** [comment]
Je viens de passer en bêta 4, pas de changement. Ou faudrait-il que je passe en mode standard ? Je suis actuellement en mode historique

**Comment by pjeantaud** [comment]
Salut,

Dans l’integration LinkyTIC, quels sont les capteurs associés ? Capture d’ecran ?
Patrick JEANTAUD
Envoyé de mon iPad

**Comment by Anoxym** [comment]
![Screenshot 2024-12-10 at 5 37 22 PM](https://github.com/user-attachments/assets/69e5e377-22d5-4578-b7e9-2f5fca2caf14)
![Screenshot 2024-12-10 at 5 37 49 PM](https://github.com/user-attachments/assets/2eca0dd2-5233-4a2d-9168-16e9fab1a080)

Tu parles des entités ?

**Comment by pjeantaud** [comment]
Dans la page Intégration de LinkyTIC tu dois voir ceci: 
![Capture d’écran 2024-12-10 à 19 00 06](https://github.com/user-attachments/assets/f1ce9f58-a2bb-495b-a78f-b56ae3ef6864)

Tu suis le lien 1 appareil ça va te lister tous les capteurs avec en face leur valeurs:
![Capture d’écran 2024-12-10 à 18 57 37](https://github.com/user-attachments/assets/290ab3db-5dfd-4fa7-b2ed-08b65d984f50)

Plus bas, tu as un bouton ajouter au tableau de bord ; moi je ne suis créé un tableau de bord Linky, comme ça je vois tout d'un seul coup d'oeil. Et plus bas encore, tu as les valeurs de Diagnostic.

Comme je suis en TIC Standard et toi en Historique, il y a plein de choses en plus.

**Comment by Anoxym** [comment]
Oui effectivement j'ai moins de capteur. J'ai demandé à passer en standard, j'ai bien ROUGE en couleur du lendemain par contre toujours HCJB, edf m'a confirmé qu'il n'y avait pas de premier jour rouge offert, j'ai en attendant installé l'api rte pour avoir la couleur

**Comment by Anoxym** [comment]
Mon linky est passé en standard effectivement j'ai beaucoup plus de données.

Par contre, la couleur du jour n'est toujours pas bonne, ce mercredi 11/12 est annoncé comme jour rouge et je récupère jour blanc en info : 

![image](https://github.com/user-attachments/assets/2c839c7d-c4ed-4de7-aa4d-fb4b2880815e)

**Comment by pjeantaud** [comment]
Salut,

Bizarre tout ça.
Pour l’histoire du jour rouge offert, il semble que ce soit le temps que le Linky reçoive la modification pour Tempo, j’ai vu ça à plusieurs reprises sur le forum PV.

**Comment by Anoxym** [comment]
Hello

Cela a l'air de s'établir tout doucement, il y'a un endroit ou je peux trouver la correspondance des index au niveau des consommation ? Pour la partie fournisseur/distributeur, fournisseur c'est l'énergie achetée et distributeur revendue ?

**Comment by pjeantaud** [comment]
Salut, on n'a pas la même config notamment car je suis producteur.
Chez moi:
Linky Energie active soutirée fournisseur, index 01 = HC Bleu
Linky Energie active soutirée fournisseur, index 02 = HP Bleu
Linky Energie active soutirée fournisseur, index 03 = HC Blanc
Linky Energie active soutirée fournisseur, index 04 = HP Blanc
Linky Energie active soutirée fournisseur, index 05 = HC Rouge
Linky Energie active soutirée fournisseur, index 06 = HP Rouge

Verifie la valeur de tes index par rapport à ce que le Linky affiche, tu vas trouver la bonne logique.

**Comment by Anoxym** [comment]
Hello

C'est tout bon j'ai récupéré les index, pour les couleurs j'utilise l'api RTE qui m'a l'air plus précis que le retour linky.

Dernière question, est ce que je peux retirer les pointes mobiles ? Je ne sais pas à quoi cela correspond mais je les ai en unavailable

**Comment by tomleglaunec** [comment]
Les pointes mobiles sont indisponibles car non envoyées par la Tic mais définies dans la spec Enedis, je ne suis pas sûr de quand les données sont envoyées, les capteurs peuvent être désactivés/cachés sans crainte depuis l'interface HA

**Comment by Anoxym** [comment]
C'est tout bon pour les couleurs : 

![Screenshot 2024-12-22 at 8 07 19 PM](https://github.com/user-attachments/assets/67034915-c1f2-4a99-b496-b9203495a91b)
