### ISSUE TITLE
Quelques remarques concernant le mode standard

### ISSUE THREAD

**Issue by pjeantaud** [hekmon/linkytic#53]
Bonjour,

Tout d'abord voici mon profil d'utilisateur:
- Compteur monophasé 60 A généralisation Linky G3 SAGEM / SAGEMCOM
- je suis producteur photovoltaïque en vente de surplus et non en vente totale, ce qui implique que je n'ai qu'un seul Linky, celui ci
- LinkyTIC 3.0.0 beta 4 tourne sur HA avec un RPI3B+ relié à l'interface MicroTeleinfo V3 de Charles Hallard
- j'ai un contrat Tempo depuis plus d'un an

Bien avant de demander mon passage de TIC Historique à Standard, j'utilisais déjà un délesteur Tempo qui fonctionnait parfaitement en mode Historique ; il est précisé dans le Readme : 
> Mode historique
> Le mode historique est le plus commun (existant pré Linky) : il est activé par défault à moins que vous soyez producteur d'énergie.
> 
Ceci est inexact, car le fait d'être Producteur d'énergie n'impose nullement le passage à la TIC Standard, c'est juste pour rectification.

Par ailleurs, je souhaite vous soumettre la capture d'écran suivante qui m'interpelle sur plusieurs points:
![Capture d’écran 2024-12-21 à 09 51 07](https://github.com/user-attachments/assets/9d6ea99e-3d3e-4373-8bf2-09f5383f1c05)

1. Le mode Producteur affiche "Désactivé" alors que je le suis, doit on le comprendre comme "Vente de surplus"?
2. Le Statut couleur du jour tempo affiche "Blanc" alors que nous sommes actuellement en Bleu (voir le Tarif fournisseur en cours HP BLEU qui lui est juste)
3. Le Statut couleur du lendemain tempo reste désespérément à "Pas d'annonce", même après 20H?

Voici le contenu du journal concerné:
`2024-12-21 10:51:55.709 DEBUG (LinkyTIC for /dev/ttyACM0) [custom_components.linkytic.serial_reader] line to parse: b'STGE\t013AC501\tS\n'
2024-12-21 10:51:55.709 DEBUG (LinkyTIC for /dev/ttyACM0) [custom_components.linkytic.serial_reader] line checksum is valid
2024-12-21 10:51:55.710 DEBUG (LinkyTIC for /dev/ttyACM0) [custom_components.linkytic.serial_reader] read the following values: STGE -> {'value': '013AC501', 'timestamp': None}
2024-12-21 10:51:55.767 DEBUG (LinkyTIC for /dev/ttyACM0) [custom_components.linkytic.serial_reader] line to parse: b'\n'
`

Merci de clarifier ma lanterne et merci encore pour ce développement.

**Comment by tomleglaunec** [comment]
Merci pour vos retours et surtout pour le log !
Ayant un contrat base, je n'ai jamais vérifié le décodage avec une valeur réelle autre que celui de mon compteur... Il y a effectivement un bug dans le décodage de l'intégration car le STGE `013AC501` indique une couleur du jour Bleu et le mode producteur activé.

Je travaille sur le correctif

**Comment by pjeantaud** [comment]
Merci Tom

**Comment by tomleglaunec** [comment]
Une nouvelle pre-release est disponible, j'attends vos retours sur ce sujet

**Comment by pjeantaud** [comment]
Bonjour Tom,

Les problèmes évoqués (mode Producteur, couleur Tempo du jour) semblent avoir été résolus:

![Capture d’écran 2024-12-22 à 11 35 19](https://github.com/user-attachments/assets/e5f7e6dc-cc56-47af-adec-d970b7958335)

Suite à la mise à jour, voici le contenu du journal:

![Capture d’écran 2024-12-22 à 11 39 07](https://github.com/user-attachments/assets/a32116c2-9d46-4c2e-b659-5cb442a678d4)

Pour la couleur du lendemain, je ferai un topo ce soir après 20H.
Merci !
