### ISSUE TITLE
ZLinky_TIC

### ISSUE THREAD

**Issue by Binifada1956** [hekmon/linkytic#7]
Bonjour

Je suis désolé de m'adresser à vous ici. Mais je ne sais pas comment vous joindre autrement !

Est-ce que linkytic fonctionne aussi en combinaison avec le Lixee ZLinky_TIC. Mon compteur se trouve à environ 20 mètres de la maison.

Je voudrais utiliser le module avec rtetempo dans Homeassistant.

Cdt
Bini

**Comment by hekmon** [comment]
Bonjour,

Aucun soucis, ce vecteur de contact est tout à fait légitime.

Par contre, cette intégration n'est pas compatible [ZLinky_TIC](https://lixee.fr/produits/37-zigate-usb-ttl-3770014375148.html). En effet est elle désigné pour parler (enfin écouter) le TIC de Enedis directement au travers d'une connection série, là ou le ZLinky_TIC s'en charge lui même avant de transmettre les informations par zigbee.

Si vous devez utiliser un module zigbee, je vous conseille de plutôt regarder [ZHA](https://www.home-assistant.io/integrations/zha/) ou [Zigbee2MQTT](https://www.zigbee2mqtt.io/) :)

PS : de mémoire il y a eu bcp de mise à jour de firmware du ZLinky_TIC nottamment pour améliorer la compatibilité ZHA, pensez à bien vous assurer d'avoir la dernière version si vous partez dans cette direction là.

**Comment by hekmon** [comment]
Aussi, si vous cherchez un adaptateur ZigBee, [celui-ci](https://www.amazon.fr/SONOFF-EFR32MG21-Coordinator-Universelle-Passerelle/dp/B0B6P22YJC/) est relativement connu et compatible avec les 2 solutions ci dessus.

**Comment by Binifada1956** [comment]
Merci beaucoup pour vos réponsesCdtBiniMit freundlichen Grüßen Am 19.02.2023 um 11:16 schrieb Edouard Hur ***@***.***>:﻿
Bonjour,
Aucun soucis, ce vecteur de contact est tout à fait légitime.
Par contre, cette intégration n'est pas compatible ZLinky_TIC. En effet est elle désigné pour parler (enfin écouter) le TIC de Enedis directement au travers d'une connection série, là ou le ZLinky_TIC s'en charge lui même avant de transmettre les informations par zigbee.
Si vous devez utiliser un module zigbee, je vous conseille de plutôt regarder ZHA ou Zigbee2MQTT :)
PS : de mémoire il y a eu bcp de mise à jour de firmware du ZLinky_TIC nottamment pour améliorer la compatibilité ZHA, pensez à bien vous assurer d'avoir la dernière version si vous partez dans cette direction là.
