### ISSUE TITLE
Intégration avec Home Assistant electricity grid

### ISSUE THREAD

**Issue by kbouh320** [hekmon/linkytic#8]
Bonjour,

Merci pour ce superbe module, vous avez vraiment fait un super boulot.
En parcourant les pages de home assistant j'ai pu remarquer leur page native de gestion des couts d'électricité.
Serait-il possible de rendre l'entité de puissance apparente sélectionnable comme source de statistique dans le système de grid de home assistant ?

Merci

https://www.home-assistant.io/docs/energy/electricity-grid/
https://www.home-assistant.io/more-info/statistics/

**Comment by hekmon** [comment]
Bonjour @kbouh320,

Merci tout d'abord pour votre retour, c'est toujours agréable d'en avoir après avoir passé autant d'heures sur une intégration.

Par contre je ne suis pas bien certain de comprendre ce que vous cherchez à accomplir ? La sonde de puissance apparente possède bien tous les attributs qu'elle est [sensée avoir](https://github.com/hekmon/linkytic/blob/v2.0.1/custom_components/linkytic/sensor.py#L210-L220) (device class, state class et unit of measurement).

Pourquoi cherchez vous à utiliser cette sonde en particulier dans le système de gestion de l'énergie Home Assistant ? Comme la [documentation](https://www.home-assistant.io/docs/energy/faq/) l'indique le panel Énergie de Home Assistant a besoin de sondes "Energy" et non "Power" (et la sonde de puissance apparente est bien une sonde de type "Power"). La seconde section indique un moyen de créer une sonde Energy à partir d'une sonde Power si celle-ci est mise à jour suffisamment souvent. Mais:

- Cela restera une approximation
- Si vous utilisez ce plugin vous avez déjà des sondes de types Energy compatibles avec le module Énergie de Home Assistant et qui plus est ne sont pas des sondes de mesures mais les sondes de références de votre Linky utilisé par GRDF pour transmettre à votre fournisseur d'électricité.

Autant donc récupérer la source, plutôt que de tenter une approximation de celle-ci. En sélectionnant directement les sondes de type Énergy dans la configuration du panneau Énergie de Home Assistant:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/3418467/227513297-66daa9f9-f3d0-42cb-8149-5bc333a99e14.png">

Vous obtenez la lecture de votre consommation la plus précise possible quand à votre consommation réelle:
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/3418467/227513534-4e2cc946-3c88-4c37-87ea-c275a73e8d74.png">

Ou alors je n'ai pas compris votre problématique auquel cas il va me falloir un peu plus de détails et d'explication afin de pouvoir vous aider :)

**Comment by hekmon** [comment]
Sans réponse de votre part je me permets de fermer l'issue
